import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography } from '@/src/theme';

const { width: screenWidth, height: screenHeight } = Dimensions.get('window');

export const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContainer: {
    backgroundColor: colors.white,
    borderRadius: 20,
    width: screenWidth * 0.92,
    maxHeight: screenHeight * 0.85,
    flexDirection: 'column',
    overflow: 'hidden',
    shadowColor: colors.black,
    shadowOffset: {
      width: 0,
      height: 4,
    },
    shadowOpacity: 0.3,
    shadowRadius: 10,
    elevation: 10,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderBottomWidth: 1,
    borderBottomColor: colors.gray200,
  },
  title: {
    fontSize: typography.fontSize['2xl'],
    fontWeight: typography.fontWeight.bold,
    color: colors.secondary,
  },
  content: {
    flexGrow: 1,
    flexShrink: 1,
    paddingHorizontal: 24,
    paddingTop: 20,
  },
  instructionBanner: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: 8,
    paddingVertical: 6,
    paddingHorizontal: 16,
    marginBottom: 20,
    backgroundColor: 'rgba(152, 170, 236, 0.15)',
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(152, 170, 236, 0.5)',
  },
  instructionTextContainer: {
    flex: 1,
    gap: 1,
  },
  instructionText: {
    fontSize: typography.fontSize.xs,
    color: colors.gray700,
    lineHeight: 16,
  },
  instructionTextBold: {
    fontWeight: typography.fontWeight.bold,
    color: colors.schedule,
  },
  legendContainer: {
    flexDirection: 'row',
    justifyContent: 'flex-start',
    alignItems: 'center',
    marginBottom: 16,
    paddingHorizontal: 4,
  },
  legendItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  legendBox: {
    width: 36,
    height: 18,
    backgroundColor: colors.schedule,
    borderRadius: 4,
    borderWidth: 0.3,
    borderColor: colors.schedule,
  },
  legendText: {
    fontSize: typography.fontSize.sm,
    fontWeight: typography.fontWeight.medium,
    color: colors.gray600,
  },
  scheduleContainer: {
    borderWidth: 1,
    borderColor: colors.gray200,
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
    borderBottomLeftRadius: 0,
    borderBottomRightRadius: 0,
    overflow: 'hidden',
  },
  tableHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 1,
    borderBottomColor: colors.gray200,
    backgroundColor: colors.gray100,
  },
  headerHourCell: {
    width: 60,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerDayCell: {
    flex: 1,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerText: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.semibold,
    color: colors.schedule,
  },
  row: {
    flexDirection: 'row',
    alignItems: 'center',
    borderBottomWidth: 0.3,
    borderBottomColor: colors.gray100,
  },
  hourCell: {
    width: 60,
    height: 32,
    justifyContent: 'center',
    alignItems: 'center',
  },
  hourText: {
    fontSize: 11,
    fontWeight: typography.fontWeight.semibold,
    color: colors.schedule,
  },
  dayCell: {
    flex: 1,
    height: 32,
    borderWidth: 0.3,
    borderColor: colors.gray100,
    backgroundColor: colors.white,
    margin: 2,
    borderRadius: 4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dayCellActive: {
    backgroundColor: colors.schedule,
    borderColor: colors.schedule,
  },
  extraHoursButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 10,
    marginTop: 0,
    marginBottom: 8,
    marginHorizontal: 0,
    backgroundColor: colors.white,
    borderWidth: 1.5,
    borderColor: colors.schedule,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
  },
  extraHoursText: {
    fontSize: typography.fontSize.xs,
    fontWeight: typography.fontWeight.medium,
    color: colors.schedule,
  },
  footer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 20,
    paddingHorizontal: 24,
    borderTopWidth: 1,
    borderTopColor: colors.gray200,
  },
  cancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: colors.gray300,
    backgroundColor: colors.white,
    alignItems: 'center',
    justifyContent: 'center',
  },
  cancelButtonText: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.semibold,
    color: colors.secondary,
  },
  saveButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    borderRadius: 12,
    backgroundColor: colors.schedule,
    shadowColor: colors.schedule,
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  saveButtonText: {
    fontSize: typography.fontSize.base,
    fontWeight: typography.fontWeight.bold,
    color: colors.white,
  },
});
